rm(list=ls())

ground<-read.csv("GroundContacts.csv", header=T)
plan<-read.csv("ManeuverPlan.csv")
payload<-read.csv("Payloadevents.csv")
rpoplan<-read.csv("Rpoplan.csv")

d1<-read.csv("ManeuverBranchId1.csv")
d2<-read.csv("ManeuverBranchId2.csv")
d3<-read.csv("ManeuverBranchId3.csv")
d4<-read.csv("ManeuverBranchId4.csv")
d5<-read.csv("ManeuverBranchId5.csv")
d6<-read.csv("ManeuverBranchId6.csv")
d7<-read.csv("ManeuverBranchId7.csv")
d8<-read.csv("ManeuverBranchId8.csv")
d9<-read.csv("ManeuverBranchId9.csv")
d10<-read.csv("ManeuverBranchId10.csv")
d11<-read.csv("ManeuverBranchId11.csv")
d12<-read.csv("ManeuverBranchId12.csv")
d13<-read.csv("ManeuverBranchId13.csv")
d14<-read.csv("ManeuverBranchId14.csv")
d15<-read.csv("ManeuverBranchId15.csv")
d16<-read.csv("ManeuverBranchId16.csv")
d17<-read.csv("ManeuverBranchId17.csv")
d18<-read.csv("ManeuverBranchId18.csv")
d19<-read.csv("ManeuverBranchId19.csv")
d20<-read.csv("ManeuverBranchId20.csv")
d21<-read.csv("ManeuverBranchId21.csv")
d22<-read.csv("ManeuverBranchId22.csv")
d23<-read.csv("ManeuverBranchId23.csv")
d24<-read.csv("ManeuverBranchId24.csv")
d25<-read.csv("ManeuverBranchId25.csv")
d26<-read.csv("ManeuverBranchId26.csv")
d27<-read.csv("ManeuverBranchId27.csv")
d28<-read.csv("ManeuverBranchId28.csv")
d29<-read.csv("ManeuverBranchId29.csv")
d30<-read.csv("ManeuverBranchId30.csv")
d31<-read.csv("ManeuverBranchId31.csv")
d32<-read.csv("ManeuverBranchId32.csv")
d33<-read.csv("ManeuverBranchId33.csv")
d34<-read.csv("ManeuverBranchId34.csv")
d35<-read.csv("ManeuverBranchId35.csv")
d36<-read.csv("ManeuverBranchId36.csv")
d37<-read.csv("ManeuverBranchId37.csv")
d38<-read.csv("ManeuverBranchId38.csv")
d39<-read.csv("ManeuverBranchId39.csv")
d40<-read.csv("ManeuverBranchId40.csv")
d41<-read.csv("ManeuverBranchId41.csv")
d42<-read.csv("ManeuverBranchId42.csv")
d43<-read.csv("ManeuverBranchId43.csv")
d44<-read.csv("ManeuverBranchId44.csv")
d45<-read.csv("ManeuverBranchId45.csv")
d46<-read.csv("ManeuverBranchId46.csv")
d47<-read.csv("ManeuverBranchId47.csv")

list.files(pattern=".csv")

